spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch
    username: root
    password:
  sql:
    init:
      platform: mysql
  batch:
    jdbc:
      initialize-schema: always
